In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.10.0+cpu


In [ ]:
# Scalars

scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
# Vectors

vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
# Matrix

matrix = torch.tensor([[7,8],
                       [9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
# Tensors

tensor = torch.tensor([[1,2,3],
                        [3,6,9],
                        [2,4,5]])
tensor

tensor.ndim

tensor.shape

torch.Size([3, 3])

### Random Tensors

In [ ]:
random_tensors = torch.rand(5,5)
random_tensors

tensor([[0.4459, 0.5401, 0.5957, 0.1394, 0.1268],
        [0.5149, 0.7107, 0.5117, 0.3647, 0.5461],
        [0.1997, 0.3937, 0.7161, 0.9439, 0.6217],
        [0.1131, 0.2830, 0.8022, 0.9592, 0.3569],
        [0.8589, 0.0743, 0.9921, 0.0017, 0.1946]])

In [ ]:
random_image_size_tensor = torch.rand(size=(224,224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros And Ones

In [ ]:
zeros = torch.zeros(size=(5,4))
zeros

#zeros.dtype

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones = torch.ones(size=(5,4))
ones

#ones.dtype

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### Creating a range of tensors and tensors like

In [ ]:
range = torch.arange(start=0, end=500, step=50)
range

tensor([  0,  50, 100, 150, 200, 250, 300, 350, 400, 450])

### Tensor datatypes


In [ ]:
# float 32 tensor

float_32_tensor = torch.tensor([3.0, 5.0, 8.0],
                                dtype=None, # what datatype is the tensor (float32 single precision or float16 half precision)
                                device=None,
                                requires_grad=False)
float_32_tensor


tensor([3., 5., 8.])

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 5., 8.], dtype=torch.float16)

In [ ]:
float_32_tensor * float_16_tensor

tensor([ 9., 25., 64.])

### Getting information from tensors

In [ ]:
# create a tenseor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.4695, 0.1880, 0.1399, 0.6052],
        [0.8518, 0.6064, 0.2091, 0.9058],
        [0.0418, 0.2308, 0.1929, 0.9987]])

In [ ]:
# find out details about some tensors
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.4695, 0.1880, 0.1399, 0.6052],
        [0.8518, 0.6064, 0.2091, 0.9058],
        [0.0418, 0.2308, 0.1929, 0.9987]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating tensors (tensor operations)

In [ ]:
 # matrix multiplication
tensor = torch.tensor([1,2,3])
tensor * tensor

tensor([1, 4, 9])

In [ ]:
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
tensor_a = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])

tensor_b = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])

torch.mm(tensor_a, tensor_b.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [ ]:
matriz = torch.tensor([[1, 2], [3, 4]], dtype=torch.float16)
matriz

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float16)

### Reshaping, stacking, squeeze and unsqueze

In [ ]:
x = torch.arange(1., 13.)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]),
 torch.Size([12]))

In [ ]:
# add extra dimension

x_reshaped = x.reshape(6, 2)
x_reshaped, x_reshaped.shape

(tensor([[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.],
         [11., 12.]]),
 torch.Size([6, 2]))

In [ ]:
# chnage the view
z = x.view(6, 2)
z, z.shape

(tensor([[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.],
         [11., 12.]]),
 torch.Size([6, 2]))

In [ ]:
# stack tensors
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[ 1.,  1.,  1.,  1.],
        [ 2.,  2.,  2.,  2.],
        [ 3.,  3.,  3.,  3.],
        [ 4.,  4.,  4.,  4.],
        [ 5.,  5.,  5.,  5.],
        [ 6.,  6.,  6.,  6.],
        [ 7.,  7.,  7.,  7.],
        [ 8.,  8.,  8.,  8.],
        [ 9.,  9.,  9.,  9.],
        [10., 10., 10., 10.],
        [11., 11., 11., 11.],
        [12., 12., 12., 12.]])

### Indexing (selecting data from tensors)
similar indexing with numpy

In [ ]:
import torch

x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
print(x[0][2][2])

tensor(9)


### Pytorch tensor and numpy

In [ ]:
import torch
import numpy as np

array = np.arange(2.0, 10.0)
tensor = torch.from_numpy(array)
array, tensor

(array([2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64))

In [ ]:
tensor = tensor +1
tensor

tensor([ 3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=torch.float64)

### Reproducibility


In [ ]:
import torch

random_tensor_a = torch.rand(3, 4)
random_tensor_b = torch.rand(3, 4)

print(random_tensor_a)
print(random_tensor_b)
print(random_tensor_a == random_tensor_b)

tensor([[0.6951, 0.8969, 0.9923, 0.0641],
        [0.8455, 0.2435, 0.4304, 0.6878],
        [0.0791, 0.6951, 0.3248, 0.9259]])
tensor([[0.6723, 0.0715, 0.9595, 0.9128],
        [0.2450, 0.2004, 0.6239, 0.6046],
        [0.4363, 0.6238, 0.4077, 0.9448]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# random but reproducible tensor
import torch

# set random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_c = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tenser_d = torch.rand(3, 4)

print(random_tensor_c)
print(random_tenser_d)
print(random_tensor_c == random_tenser_d)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


### Running tensors and pytorch objects on the GPU
GPU = Faster computation numbers, CUDA + NVIDIA hardware + Pytorch

In [1]:
!nvidia-smi

Wed May 27 11:29:58 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   46C    P8             10W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [2]:
# check gpu access
import torch
torch.cuda.is_available()

True

In [4]:
# setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [6]:
# count numbers of device
torch.cuda.device_count()

1

### Putting tensors (and models) on the gpu

For more faster computations


In [9]:
import torch
tensor = torch.tensor([2, 4, 6])

# tensor not on gpu
print(tensor, tensor.device)

tensor([2, 4, 6]) cpu


In [10]:
# move to gpu
gpu_tensor = tensor.to(device)
gpu_tensor

tensor([2, 4, 6], device='cuda:0')

In [11]:
cpu_tensor = gpu_tensor.cpu().numpy()
cpu_tensor

array([2, 4, 6])