### **2. Create a random tensor with shape (7, 7).**

In [16]:
tensor_a = torch.rand(7, 7)
print(tensor_a, tensor_a.shape)

tensor([[0.4640, 0.0967, 0.4759, 0.7859, 0.7996, 0.3164, 0.2332],
        [0.2472, 0.9224, 0.7902, 0.2853, 0.2519, 0.9062, 0.6709],
        [0.3140, 0.2109, 0.3118, 0.1921, 0.3442, 0.7509, 0.6725],
        [0.6700, 0.2822, 0.8471, 0.7969, 0.1759, 0.2590, 0.5607],
        [0.6895, 0.8022, 0.9403, 0.7324, 0.6804, 0.9558, 0.8109],
        [0.4761, 0.6519, 0.7828, 0.4243, 0.8055, 0.6928, 0.6727],
        [0.8450, 0.7559, 0.8540, 0.1633, 0.9569, 0.5000, 0.2142]]) torch.Size([7, 7])


### **3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).**

In [18]:
tensor_b = torch.rand(1, 7)

torch.matmul(tensor_a, tensor_b.T)

tensor([[1.7149],
        [2.1584],
        [1.7477],
        [2.0214],
        [3.0907],
        [2.4295],
        [2.2770]])

### **4. Set the random seed to 0 and do 2 & 3 over again.**

In [28]:
RANDOM_SEED = 0

tensor_c = torch.rand(7, 7)
torch.manual_seed=(RANDOM_SEED)

tensor_d = torch.rand(1, 7)
torch.manual_seed=(RANDOM_SEED)

print(tensor_c, tensor_d)

tensor([[0.5328, 0.1539, 0.5585, 0.1808, 0.4124, 0.6533, 0.7974],
        [0.1100, 0.1073, 0.0672, 0.0182, 0.4177, 0.4394, 0.6022],
        [0.0199, 0.9231, 0.6538, 0.3551, 0.6025, 0.9720, 0.3531],
        [0.5301, 0.0480, 0.6589, 0.2717, 0.2191, 0.6817, 0.5746],
        [0.8866, 0.7908, 0.8971, 0.7872, 0.1112, 0.2858, 0.6531],
        [0.1529, 0.7432, 0.6438, 0.6479, 0.2009, 0.4177, 0.5641],
        [0.3400, 0.7230, 0.3232, 0.1700, 0.1247, 0.4318, 0.3401]]) tensor([[0.0694, 0.4939, 0.1289, 0.8713, 0.8354, 0.8402, 0.7038]])


### **5. Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one). If there is, set the GPU random seed to 1234.**

In [19]:
import torch

device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"working on: {device}\n")

torch.manual_seed(1234)
torch.cuda.manual_seed(1234)

tensor_a_cpu = torch.rand(7, 7)
tensor_b_cpu = torch.rand(1, 7)

tensor_a_gpu = tensor_a_cpu.to(device)
tensor_b_gpu = tensor_b_cpu.to(device)

print(f"{tensor_a_gpu}\n{tensor_b_gpu}")

working on: cuda

tensor([[0.0290, 0.4019, 0.2598, 0.3666, 0.0583, 0.7006, 0.0518],
        [0.4681, 0.6738, 0.3315, 0.7837, 0.5631, 0.7749, 0.8208],
        [0.2793, 0.6817, 0.2837, 0.6567, 0.2388, 0.7313, 0.6012],
        [0.3043, 0.2548, 0.6294, 0.9665, 0.7399, 0.4517, 0.4757],
        [0.7842, 0.1525, 0.6662, 0.3343, 0.7893, 0.3216, 0.5247],
        [0.6688, 0.8436, 0.4265, 0.9561, 0.0770, 0.4108, 0.0014],
        [0.5414, 0.6419, 0.2976, 0.7077, 0.4189, 0.0655, 0.8839]],
       device='cuda:0')
tensor([[0.8083, 0.7528, 0.8988, 0.6839, 0.7658, 0.9149, 0.3993]],
       device='cuda:0')


### **6. Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed).**
### **7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).**
### **8. Find the maximum and minimum values of the output of 7.**
### **9. Find the maximum and minimum index values of the output of 7.**

In [3]:
import torch

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
SEED = 1234
print(f"working on: {DEVICE}\n")

def create_tensor(shape, seed=SEED, device=DEVICE):

  if DEVICE == "cuda":
    torch.cuda.manual_seed(seed)
  else:
    torch.manual_seed(seed)

  return torch.rand(shape, device=device)

tensor_e = create_tensor(shape=(2, 3))
tensor_f = create_tensor(shape=(2, 3))
print(f"{tensor_e}\n{tensor_f}\n")

# matrix multi
matrix_mul = torch.matmul(tensor_e, tensor_f.T)
print(f"Matrix result: {matrix_mul}\n")

# min and max
max_value = matrix_mul.max()
min_value = matrix_mul.min()
print(f"Max value: {max_value}\nMin value: {min_value}")

# min and max index
max_index = matrix_mul.argmax()
min_index = matrix_mul.argmin()
print(f"Max index: {max_index}\nMin index: {min_index}")

working on: cuda

tensor([[0.1272, 0.8167, 0.5440],
        [0.6601, 0.2721, 0.9737]], device='cuda:0')
tensor([[0.1272, 0.8167, 0.5440],
        [0.6601, 0.2721, 0.9737]], device='cuda:0')

Matrix result: tensor([[0.9792, 0.8358],
        [0.8358, 1.4578]], device='cuda:0')

Max value: 1.4577524662017822
Min value: 0.8358409404754639
Max index: 3
Min index: 1


### **10. Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.**

In [1]:
import torch

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
SEED = 7
print(f"working on {DEVICE}\n")


def create_tensor(shape, seed=SEED):
  if DEVICE == "cuda":
    torch.cuda.manual_seed(SEED)
  else:
    torch.manual_seed(SEED)

  return torch.rand(shape, device=DEVICE)

tensor_a = create_tensor(shape=(1, 1, 1, 10))
tensor_b = tensor_a.squeeze()

print(f"{tensor_a}\n{tensor_a.shape}\n{tensor_b}\n{tensor_b.shape}")

working on cuda

tensor([[[[0.9546, 0.4950, 0.9420, 0.5926, 0.6996, 0.2087, 0.6753, 0.4810,
           0.6333, 0.5733]]]], device='cuda:0')
torch.Size([1, 1, 1, 10])
tensor([0.9546, 0.4950, 0.9420, 0.5926, 0.6996, 0.2087, 0.6753, 0.4810, 0.6333,
        0.5733], device='cuda:0')
torch.Size([10])
